//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aseguradora.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbAseguradoraEntities : DbContext
    {
        public DbAseguradoraEntities()
            : base("name=DbAseguradoraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TblAseguradora> TblAseguradora { get; set; }
        public virtual DbSet<TblCliente> TblCliente { get; set; }
        public virtual DbSet<TblFormaDePago> TblFormaDePago { get; set; }
        public virtual DbSet<TblMarca> TblMarca { get; set; }
        public virtual DbSet<TblMovimientos> TblMovimientos { get; set; }
        public virtual DbSet<TblProducto> TblProducto { get; set; }
        public virtual DbSet<TblProductoCliente> TblProductoCliente { get; set; }
        public virtual DbSet<TblTipoProducto> TblTipoProducto { get; set; }
        public virtual DbSet<TblTipoVehiculo> TblTipoVehiculo { get; set; }
        public virtual DbSet<TblVehiculo> TblVehiculo { get; set; }
        public virtual DbSet<TblVehiculoCliente> TblVehiculoCliente { get; set; }
        public virtual DbSet<TblDepartamento> TblDepartamento { get; set; }
        public virtual DbSet<TblMunicipio> TblMunicipio { get; set; }
    }
}
