//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aseguradora.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblCliente()
        {
            this.TblProductoCliente = new HashSet<TblProductoCliente>();
        }
    
        public int IdCliente { get; set; }
        public string PrimerNombre { get; set; }
        public string SegundoNombre { get; set; }
        public string PrimerApellido { get; set; }
        public string SegundoApellido { get; set; }
        public string ApellidoCasada { get; set; }
        public string Departamento { get; set; }
        public string Municipio { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
        public string TelefonoSecundario { get; set; }
        public string TelefonoCelular { get; set; }
        public string NIT { get; set; }
        public string DPI { get; set; }
        public string CorreoElectronico { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public string ProfesionUOficio { get; set; }
        public bool Activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblProductoCliente> TblProductoCliente { get; set; }
    }
}
