//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aseguradora.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMovimientos
    {
        public int IdMovimiento { get; set; }
        public int IdProductoCliente { get; set; }
        public string Documento { get; set; }
        public decimal Valor { get; set; }
    
        public virtual TblProductoCliente TblProductoCliente { get; set; }
        public virtual TblProductoCliente TblProductoCliente1 { get; set; }
    }
}
