//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aseguradora.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPagina
    {
        public int IdPagina { get; set; }
        public string Mensaje { get; set; }
        public string Accion { get; set; }
        public string Controlador { get; set; }
        public int BHabilitado { get; set; }
    }
}
