//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aseguradora.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblProductoCliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblProductoCliente()
        {
            this.TblMovimientos = new HashSet<TblMovimientos>();
            this.TblVehiculoCliente = new HashSet<TblVehiculoCliente>();
        }
    
        public int IdProductoCliente { get; set; }
        public int IdTipoProducto { get; set; }
        public int IdCliente { get; set; }
        public int IdFormaDePago { get; set; }
        public string DocumentoPoliza { get; set; }
        public System.DateTime FechaInicial { get; set; }
        public Nullable<System.DateTime> FechaFinal { get; set; }
        public Nullable<decimal> ValorGeneral { get; set; }
        public decimal ValorPoliza { get; set; }
        public decimal ValorActual { get; set; }
        public decimal PrimaAnual { get; set; }
        public decimal PrimaNeta { get; set; }
    
        public virtual TblCliente TblCliente { get; set; }
        public virtual TblFormaDePago TblFormaDePago { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMovimientos> TblMovimientos { get; set; }
        public virtual TblTipoProducto TblTipoProducto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblVehiculoCliente> TblVehiculoCliente { get; set; }
        public virtual TblMovimientos TblMovimientos1 { get; set; }
    }
}
