//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aseguradora.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblVehiculoCliente
    {
        public int IdVehiculoCliente { get; set; }
        public int IdCliente { get; set; }
        public int IdVehiculo { get; set; }
        public int Documento { get; set; }
        public string Color { get; set; }
        public string VIN { get; set; }
        public string NumeroDePlaca { get; set; }
        public int Anio { get; set; }
        public bool Activo { get; set; }
        public decimal Valor { get; set; }
        public int IdProductoCliente { get; set; }
    
        public virtual TblVehiculo TblVehiculo { get; set; }
        public virtual TblProductoCliente TblProductoCliente { get; set; }
    }
}
